'use strict';
const $=s=>document.querySelector(s);
const criteria=[
 {key:'view',name:'A view ahead',hint:'Ordinary forward-facing seats with an outward view.'},
 {key:'exit',name:'An easy exit',hint:'Less walking through the bus when your stop arrives.'},
 {key:'calm',name:'Away from door activity',hint:'A proxy for fewer door-side interruptions, not measured quietness.'},
 {key:'access',name:'An easier path to the seat',hint:'Prefer fewer obstacles; inspect the actual platform and steps.'},
 {key:'social',name:'Sitting with a friend',hint:'Look for a pair or adjacent seats without taking priority space.'}
];
const presets={balanced:[3,2,3,2,1],quick:[1,4,1,2,0],quiet:[1,1,4,1,0],view:[4,0,0,0,0],friends:[0,1,0,0,4],motion:[4,1,1,1,0]};
let bus='articulated',selected='middle',activePreset='balanced',weights=[...presets.balanced];
const zones=[
 {id:'front',name:'Front ordinary seats',short:'Front',tag:'FOR THE ROAD AHEAD',ratings:[4,2,2,3,2],description:'An ordinary forward-facing seat in the front half is a useful starting point when you want to see ahead. Choose one outside the marked priority area. A driver partition or seat orientation can limit the view.',pros:['Potential view through the windscreen or forward windows.','Less of the bus to walk through after boarding.','A practical first choice for the travel-sickness preset.'],cons:['Close to boarding, validation and front-door activity.','Some seats may be raised, sideways or marked as priority.','Not automatically the quietest or safest place.'],best:'Looking ahead, orientation, or an ordinary seat that is easy to reach.',tip:'For travel sickness, CDC favours the front of a bus. NHS advises looking ahead and avoiding reading/screens. Choose an available forward-facing seat with a useful view. No particular LPP row is guaranteed. <a href="#source-health">[6, 7]</a>',basis:'Health advice is sourced; exact zone suitability is editorial.'},
 {id:'middle',name:'Middle ordinary seats',short:'Middle',tag:'THE BALANCED CHOICE',ratings:[3,3,4,3,3],description:'Seats in the middle of a body section, away from an actual doorway, can be a practical compromise. On an articulated bus, this means the seating section before the joint, not the rotating joint itself.',pros:['Can balance distance to an exit with distance from a doorway.','An ordinary window pair can work for a longer trip.','A good place to compare the actual ride before settling in.'],cons:['Wheelchair bays and exit-door queues often interrupt the available seating.','An open seat here is not necessarily step-free.','Suspension, road surface and driving affect comfort more than a generic map.'],best:'An everyday ride or a longer journey when a suitable ordinary seat is available.',tip:'Look for a clear aisle and a seat away from a door, then check its facing direction and foot room. This guide does not claim that the middle has measured lower vibration.',basis:'Editorial trade-off, not an LPP comfort test.'},
 {id:'exit',name:'Seats beside an exit',short:'Near exit',tag:'THE SHORT-TRIP SPECIALIST',ratings:[2,4,1,4,2],description:'An ordinary aisle seat near an exit lets you prepare to leave without crossing most of the vehicle. Near the door is useful; inside the doorway is not a seating or waiting strategy.',pros:['Convenient for a journey of only a few stops.','An aisle seat avoids having to pass a seated neighbour.','The exit is easier to identify while you wait for your stop.'],cons:['People may gather beside you and move past at stops.','Door opening can bring drafts, street sound or a change in temperature.','Do not confuse nearby folding or priority seats with unrestricted seating.'],best:'Short trips and passengers who value a straightforward exit.',tip:'Use the door marked for exit and keep the opening and aisle clear. Confirm that any nearby seat is suitable for your needs and not required for a wheelchair or stroller.',basis:'Layout-based editorial advice; entry/exit guidance from LPP [4, 5].'},
 {id:'rear',name:'Rear ordinary seats',short:'Rear',tag:'FOR THE LONGER STAY',ratings:[1,2,3,1,4],description:'The rear can offer adjacent seating or a bench on some layouts. It may suit friends staying on for a while, but the actual rear seats, platform and door positions determine how convenient it is.',pros:['Some layouts offer a pair or bench for friends.','May be away from the front-door boarding activity.','Can work if you do not need to leave immediately.'],cons:['Can involve raised flooring, steps or a longer path.','On combustion vehicles, rear powertrain noise or warmth may be noticeable.','Rear-door queues, people and electric drivetrains can change that experience.'],best:'Friends or a longer journey when suitable adjacent seats are free.',tip:'Check the platform, legroom and nearest exit first. Never assume the rear is less crowded. Keep voices low: group-friendly does not mean a private compartment.',basis:'Editorial; noise and crowding have not been measured.'},
 {id:'wheel',name:'Wheel-arch seats',short:'Wheel arch',tag:'CHECK THE FOOT ROOM',ratings:[2,2,3,1,2],description:'A seat near a wheel arch can have a raised base or a shaped floor that changes where your feet fit. It is not a distinct universal row: the geometry differs between vehicles.',pros:['Can be a perfectly usable ordinary seat if the foot room works for you.','Sometimes away from a doorway.','Worth comparing with another available seat on the actual bus.'],cons:['Raised bases or intrusions may make leg position awkward.','May be a poor match for someone avoiding steps or needing easy access.','The guide cannot predict vibration from a wheel position alone.'],best:'Passengers who have checked the seat height, floor and legroom.',tip:'A useful check for taller riders: put both feet comfortably on the floor before deciding. There are no measured “bumps per row” in this guide.',basis:'Seat-geometry judgement; no vibration measurements.'},
 {id:'joint',name:'The articulated joint',short:'The joint',tag:'A PASSAGE, NOT A SEAT',ratings:null,description:'The flexible connection joins the two bus sections. Its floor changes angle as the bus turns. It is a distinctive part of the ride, but this guide treats it as a passage or marked standing space, not a recommended seat.',pros:['Connects the front and rear sections.','Can help you understand the layout as you pass through.'],cons:['Not an ordinary seated option and never included in seat rankings.','Requires attention to movement and the on-board markings.','Do not linger here just to watch the mechanism.'],best:'Moving through when necessary, using a suitable handhold and following the markings.',tip:'If you must stand, use the designated standing area and handrails. Do not sit on the joint floor or interfere with its moving parts.',basis:'Schematic explanation; follow vehicle-specific instructions.'},
 {id:'priority',name:'Priority & accessible area',short:'Priority / bay',tag:'NEEDS COME FIRST',ratings:null,description:'Marked priority seats and the designated wheelchair/stroller area are for access needs, not bonus space in the seat finder. The bay and the seats are different facilities. Their exact positions and equipment vary.',pros:['A suitable marked seat may reduce the distance or steps for someone who needs it.','A designated bay provides the intended area for a wheelchair or stroller.'],cons:['An empty bay is not an invitation to store bags or claim a private area.','Folding seats may need to be vacated for the intended bay use.','The schematic cannot identify the correct boarding door for every vehicle.'],best:'Passengers who need priority seating or the designated mobility space.',tip:'Identify the signs and ask the driver if you need the ramp or boarding assistance. Use the wheelchair/stroller position and securing equipment as instructed. The example MAN specification places a ramp at the second door; inspect your actual bus. <a href="#source-fleet">[1, 3]</a>',basis:'LPP vehicle/accessibility sources; not an exact seat map.'}
];
function availableZones(){return zones.filter(z=>z.id!=='joint'||bus==='articulated');}
function seat(x,y,fill='#b1bea3',back='#6e805d'){return `<g><rect x="${x}" y="${y}" width="27" height="34" rx="6" fill="${fill}" stroke="${back}" stroke-width="1.3"/><path d="M${x+3} ${y+28}h21" stroke="${back}" stroke-width="4" stroke-linecap="round"/></g>`;}
function drawMap(){const compact=bus==='compact',art=bus==='articulated',end=compact?708:art?858:788;let s=`<defs><pattern id="bay-lines" width="9" height="9" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><line x1="0" x2="0" y2="9" stroke="#dab676" stroke-width="2"/></pattern></defs><path d="M200 23v28m-7-8l7 8l7-8" stroke="#77886a" stroke-width="2" fill="none"/><text x="200" y="14" text-anchor="middle" font-size="9" fill="#77886a">DIRECTION OF TRAVEL</text><rect x="90" y="69" width="220" height="${end-55}" rx="28" fill="#faf9f0" stroke="#708961" stroke-width="3"/><path d="M116 75h168" stroke="#a4bbb8" stroke-width="7" stroke-linecap="round"/><rect x="108" y="92" width="64" height="54" rx="8" fill="#3b4e42"/><circle cx="143" cy="111" r="12" fill="none" stroke="#c1d0aa" stroke-width="3"/><text x="140" y="137" text-anchor="middle" font-size="8" fill="#cbd5bd">DRIVER</text><text x="200" y="174" text-anchor="middle" font-size="8" fill="#a3ad98">AISLE</text>`;
const regions=[{id:'front',x:101,y:158,w:196,h:84},{id:'middle',x:101,y:410,w:196,h:105},{id:'exit',x:223,y:407,w:74,h:75},{id:'rear',x:101,y:art?679:compact?558:581,w:196,h:compact?118:128},{id:'wheel',x:103,y:248,w:64,h:69},{id:'priority',x:102,y:326,w:86,h:68}];if(art)regions.push({id:'joint',x:93,y:548,w:214,h:73});s+=regions.map(r=>`<g data-zone="${r.id}"><rect x="${r.x}" y="${r.y}" width="${r.w}" height="${r.h}" rx="7" fill="${selected===r.id?'#c6dd84':r.id==='priority'?'#eee0bf':r.id==='joint'?'#d4dbca':'#e7eddf'}" stroke="${selected===r.id?'#658653':'none'}" stroke-width="2"/><title>${zones.find(z=>z.id===r.id).name.replace(/&/g,'&amp;')}</title></g>`).join('');
const rows=compact?[190,265,445,578,630]:art?[190,265,445,488,700,754,806]:[190,265,445,495,604,657,718];s+=rows.map(y=>{const arch=y===265;return `<g data-zone="${arch?'wheel':y<300?'front':y<550?'middle':'rear'}">`+seat(111,y,arch?'#bcbb9e':'#b1bea3')+seat(144,y,arch?'#bcbb9e':'#b1bea3')+'</g>'+`<g data-zone="${y===445?'exit':arch?'wheel':y<300?'front':y<550?'middle':'rear'}">`+seat(231,y)+seat(264,y)+'</g>';}).join('');s+=`<g data-zone="priority"><rect x="112" y="336" width="65" height="46" rx="4" fill="url(#bay-lines)" stroke="#c7a266"/><text x="145" y="356" text-anchor="middle" font-size="9" fill="#9b7646">BAY</text><text x="145" y="373" text-anchor="middle" font-size="7" fill="#9b7646">KEEP CLEAR</text>${seat(110,151,'#dbc190','#ac8a52')}</g>`;
const doors=compact?[124,351]:art?[124,351,645,824]:[124,351,751];s+=doors.map((y,i)=>`<rect x="302" y="${y}" width="14" height="40" fill="#f0d8a5" stroke="#c4a46f"/><path d="M315 ${y+8}l12 12l-12 12" fill="none" stroke="#c4a46f" stroke-width="1.5"/><text x="329" y="${y+23}" font-size="8" fill="#9a8055">${i===0?'ENTRY':'EXIT'}</text>`).join('');if(art)s+=`<g data-zone="joint">${Array.from({length:12},(_,i)=>`<path d="M96 ${553+i*5}h208" stroke="#9ba78f" stroke-width="2"/>`).join('')}<rect x="161" y="571" width="78" height="23" rx="3" fill="#eef0e5"/><text x="200" y="587" text-anchor="middle" font-size="9" fill="#748268">THE JOINT</text></g>`;s+=`<text x="45" y="206" text-anchor="middle" font-size="9" fill="#748268">FRONT</text><text x="45" y="467" text-anchor="middle" font-size="9" fill="#748268">MIDDLE</text><text x="45" y="${art?746:compact?620:650}" text-anchor="middle" font-size="9" fill="#748268">REAR</text><path d="M72 190v42M72 445v49M72 ${art?701:compact?581:610}v63" stroke="#aab99b" stroke-width="1"/><text x="200" y="${end+44}" text-anchor="middle" font-size="8" fill="#839275">ZONES, NOT AN EXACT SEAT COUNT</text>`;$('#bus-map').innerHTML=s;$('#bus-map').setAttribute('viewBox',`0 0 400 ${end+65}`);$('#bus-map').setAttribute('aria-label',`${bus} bus schematic. Selected zone: ${zones.find(z=>z.id===selected).name}. Illustrative seats, not an exact LPP seating plan.`);}
function renderZone(){const z=zones.find(z=>z.id===selected);$('#zone-buttons').innerHTML=availableZones().map((x,i)=>`<button class="zone-button" data-select-zone="${x.id}" aria-pressed="${x.id===selected}"><span>${String(i+1).padStart(2,'0')}</span>${x.short}</button>`).join('');document.querySelectorAll('[data-select-zone]').forEach(b=>b.onclick=()=>{selected=b.dataset.selectZone;renderZone();drawMap();});$('#zone-detail').innerHTML=`<span class="tag">${z.tag}</span><h3>${z.name}</h3><p class="description">${z.description}</p><div class="pros-cons"><div><h4>THE UPSIDE +</h4><ul>${z.pros.map(x=>`<li>${x}</li>`).join('')}</ul></div><div><h4>THE TRADE-OFF −</h4><ul>${z.cons.map(x=>`<li>${x}</li>`).join('')}</ul></div></div><div class="best-for"><strong>BEST FOR: ${z.best}</strong>${z.tip}</div><p class="source-tag">${z.basis}</p>`;}
function renderBus(){if(bus!=='articulated'&&selected==='joint')selected='middle';$('#bus-description').textContent={single:'12 m city-bus example · illustrative layout',articulated:'18 m city-bus example · includes the joint',compact:'Compact city-bus shape · illustrative layout'}[bus];document.querySelectorAll('[data-bus]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.bus===bus)));drawMap();renderZone();}
$('#bus-map').addEventListener('click',e=>{const g=e.target.closest('[data-zone]');if(g){selected=g.dataset.zone;drawMap();renderZone();}});document.querySelectorAll('[data-bus]').forEach(b=>b.onclick=()=>{bus=b.dataset.bus;renderBus();});
function effectiveWeights(){const w=[...weights];const trip=$('#trip').value;if(trip==='short')w[1]+=1;if(trip==='long')w[2]+=1;return w;}
function computeRanking(w){const sum=w.reduce((a,b)=>a+b,0);if(!sum)return[];return zones.filter(z=>z.ratings).map((z,index)=>({zone:z,index,score:100*z.ratings.reduce((a,r,i)=>a+r*w[i],0)/(4*sum)})).sort((a,b)=>b.score-a.score||a.index-b.index);}
function renderFinder(){const need=$('#access').value,w=effectiveWeights();const special={stepfree:{title:'A suitable seat without steps',text:'Choose a marked priority seat or suitable ordinary seat reached without steps. Check the actual floor and seat platform. Ask the driver for help if needed; the shortest, usable route matters more than a preference score.'},wheelchair:{title:'The designated wheelchair bay',text:'Identify the wheelchair symbols and boarding arrangement. Ask the driver for ramp assistance when needed. Position and secure the wheelchair according to the on-board instructions. The diagram shows an example bay, not a universal location.'},stroller:{title:'The designated stroller area',text:'Use the area marked for a stroller and follow the driver’s instructions and any wheelchair-priority arrangements. Apply the brakes and use the securing arrangement as instructed. A folding seat may need to stay free for the bay to be usable.'}};if(need!=='none'){const s=special[need];$('#recommendation').textContent=s.title;$('#recommendation-copy').textContent=s.text;$('#rankings').innerHTML='<div class="access-message">Access needs override the preference model. Priority seats and mobility bays are not scored against ordinary seats. Follow the actual signs and driver’s instructions. <a href="#source-fleet">[1, 3]</a></div>';$('#model-explanation').textContent='Your sliders are retained, but no ranking is applied while an access need is selected.';return;}
const rankings=computeRanking(w);if(!rankings.length){$('#recommendation').textContent='No preference, no false precision.';$('#recommendation-copy').textContent='All priorities are zero and the medium journey adds no extra weight. Choose any suitable available ordinary seat, leaving priority seats and access areas available.';$('#rankings').innerHTML='<div class="no-weight">Set a slider or choose a preset to compare the trade-offs.</div>';$('#model-explanation').textContent='The model has no weights, so it cannot rank a seat.';return;}
const winner=rankings[0].zone;$('#recommendation').textContent=winner.name;const motion=activePreset==='motion';$('#recommendation-copy').innerHTML=motion?'Start with an available ordinary forward-facing seat near the front and a useful view ahead. Look at a distant stable point rather than your phone. These are general CDC/NHS tips, not an LPP-tested treatment. <a href="#source-health">[6, 7]</a>':`${winner.best} Treat this as a starting point: a seat’s actual direction, platform, neighbours and availability matter.`;$('#rankings').innerHTML=rankings.map(r=>`<div class="ranking"><span>${r.zone.short}</span><div class="rank-track"><div class="rank-fill" style="width:${r.score.toFixed(2)}%"></div></div><span class="rank-value">${Math.round(r.score)}/100</span></div>`).join('');$('#model-explanation').innerHTML=`<strong>Preference-match index, not a measured comfort percentage.</strong><br>Effective weights: ${criteria.map((c,i)=>`${c.name.toLowerCase()} ${w[i]}`).join(' · ')}. ${$('#trip').value==='short'?'Short-trip exit bonus applied.':$('#trip').value==='long'?'Long-trip door-distance bonus applied.':'No journey-length bonus.'}${motion?' General guidance favours the front; an unavailable or unsuitable seat cannot be made suitable by a score.':''}`;}
function renderSliders(){ $('#sliders').innerHTML=criteria.map((c,i)=>`<div class="slider-row"><label for="weight-${c.key}">${c.name}<output id="out-${c.key}" for="weight-${c.key}">${weights[i]}</output></label><input id="weight-${c.key}" data-weight="${i}" type="range" min="0" max="4" value="${weights[i]}"><small>${c.hint}</small></div>`).join('');document.querySelectorAll('[data-weight]').forEach(input=>input.oninput=()=>{const i=Number(input.dataset.weight);weights[i]=Number(input.value);$('#out-'+criteria[i].key).textContent=weights[i];activePreset=null;document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed','false'));renderFinder();});}
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{activePreset=b.dataset.preset;weights=[...presets[activePreset]];$('#trip').value=activePreset==='quick'?'short':activePreset==='quiet'||activePreset==='friends'?'long':'medium';document.querySelectorAll('[data-preset]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderSliders();renderFinder();});$('#trip').onchange=renderFinder;$('#access').onchange=renderFinder;
function level(n){return n>=3?'high':n===2?'medium':'low';}function label(n){return n>=3?'High':n===2?'Mixed':'Low';}
$('#matrix tbody').innerHTML=zones.filter(z=>z.ratings).map(z=>`<tr><th scope="row">${z.short}</th>${z.ratings.map(n=>`<td><span class="rating ${level(n)}"><i aria-hidden="true">${n>=3?'●':n===2?'◐':'○'}</i>${label(n)}</span></td>`).join('')}</tr>`).join('');
const sideData=[['City view',4,1],['Leaving the row',1,4],['Less aisle contact',4,1],['Easy to yield seat',1,4]];$('#side-chart').innerHTML='<div class="side-row side-head"><span>EDITORIAL 0–4</span><span>WINDOW</span><span>AISLE</span></div>'+sideData.map(([name,a,b])=>`<div class="side-row"><span>${name}</span><span class="side-cell" aria-label="Window suitability ${a} out of 4">${Array.from({length:4},(_,i)=>`<i class="${i<a?'on':''}" aria-hidden="true"></i>`).join('')}</span><span class="side-cell aisle" aria-label="Aisle suitability ${b} out of 4">${Array.from({length:4},(_,i)=>`<i class="${i<b?'on':''}" aria-hidden="true"></i>`).join('')}</span></div>`).join('');
const directions=[['Forward-facing','You face the direction of travel. Check whether you can actually see ahead: a partition or another passenger can still block the view. This is the preferred starting point for the travel-sickness guidance.'],['Side-facing','You face across the aisle. It may be easier to step away from the seat, but it offers a different outward view. Do not assume its comfort matches a forward-facing seat in the same zone.'],['Rear-facing','You face against the direction of travel. It can suit a facing pair when travelling with a friend, but is a poor match if your main goal is a view of the road ahead.']];
$('#orientation-grid').innerHTML=directions.map(([name,text],i)=>`<article><svg viewBox="0 0 210 120" role="img" aria-label="${name} seat orientation relative to forward travel"><path d="M40 93V25m-8 9l8-9l8 9" stroke="#81916f" stroke-width="2" fill="none"/><text x="40" y="112" text-anchor="middle" font-size="8" fill="#81916f">TRAVEL</text><g transform="rotate(${[0,90,180][i]} 130 60)"><rect x="109" y="38" width="42" height="48" rx="8" fill="#c1d695" stroke="#728f56" stroke-width="2"/><path d="M115 78h30" stroke="#728f56" stroke-width="6" stroke-linecap="round"/><path d="M130 61V21m-6 7l6-7l6 7" fill="none" stroke="#48653d" stroke-width="2"/></g></svg><h3>${name}</h3><p>${text}</p></article>`).join('');
const scenarios=[
 ['↗','Only a few stops','Try an ordinary aisle seat close to an exit. If no suitable seat is free, stand in a marked standing area with a handhold, out of the doorway.','Avoid a rear window seat if it makes you cross a neighbour and most of the bus to leave.','quick'],
 ['◌','A quieter ride','Try a seat away from door openings. On a combustion bus, compare the rear powertrain area with the front or middle. People and the specific vehicle decide the actual noise.','“Away from doors” is a proxy. An electric bus or a noisy group can reverse the expectation.','quiet'],
 ['↟','Travel sickness','Try an ordinary forward-facing front seat with an outward view. Look ahead at a distant fixed point. Put reading and scrolling aside if they trigger symptoms. <a href="#source-health">[6, 7]</a>','A window facing a nearby wall or a sideways seat is not the same as a view ahead. No seat promises relief.','motion'],
 ['□□','With a friend','Look for an available ordinary pair or adjacent rear seats. Use one seat per person and keep conversation considerate.','Do not occupy priority seats or the mobility bay just to keep your group together.','friends'],
 ['◒','Watch Ljubljana','A window seat gives a side view without someone between you and the glass. Check for advertisements, pillars and the direction you face.','A seat near the driver is not automatically the clearest window. The aisle is easier to leave.','view'],
 ['↔','Tall or carrying a bag','Check actual knee and foot room. A raised wheel-arch floor can be awkward. Keep your bag with you, clear of the aisle and other seats.','This map has no measured legroom and does not identify a universal “extra-legroom” row.',null],
 ['▧','Reading or scrolling','If you comfortably read while travelling, choose an available ordinary seat away from the aisle traffic and doorway. Check the light and remember your stop.','If reading or screens bring on travel sickness, put them away and look ahead instead. <a href="#source-health">[6, 7]</a>',null],
 ['♿','Need easier access','Choose an appropriate marked priority seat or the designated mobility bay. Ask the driver when you need boarding help. <a href="#source-fleet">[1, 3]</a>','A low-floor vehicle can still have raised seat platforms. Access needs outrank comfort scores.',null],
 ['☀','Avoid the sun','Look at which side faces the sun on the current road segment, then choose an available seat on the opposite side. Use the geometry tool above.','Left or right depends on heading. Turns, shade and weather can change it.',null],
 ['▤','Rush-hour reality','Take a suitable available seat rather than crossing a packed bus to reach a theoretically better zone. If standing, hold on and keep access routes clear.','The finder has no live occupancy. It cannot tell you where a seat is currently free.',null]
];$('#scenario-grid').innerHTML=scenarios.map(([icon,title,text,avoid,preset])=>`<article class="scenario"><span class="icon" aria-hidden="true">${icon}</span><h3>${title}</h3><p>${text}</p><p class="avoid"><strong>WATCH OUT:</strong> ${avoid}</p>${preset?`<a href="#finder" data-scenario="${preset}">Try this preset ↗</a>`:''}</article>`).join('');document.querySelectorAll('[data-scenario]').forEach(a=>a.onclick=()=>{const b=document.querySelector(`[data-preset="${a.dataset.scenario}"]`);b.click();});
function bearingName(v){return ['North','North-east','East','South-east','South','South-west','West','North-west'][Math.round(v/45)%8];}
function shadeSide(heading,sun){const d=(sun-heading)*Math.PI/180,s=Math.sin(d);return Math.abs(s)<.18?'aligned':s>0?'left':'right';}
function renderSun(){const h=Number($('#heading').value),a=Number($('#sun-bearing').value);$('#heading-value').textContent=`${bearingName(h)} · ${h}°`;$('#sun-value').textContent=`${bearingName(a)} · ${a}°`;const side=shadeSide(h,a);$('#sun-result').textContent=side==='aligned'?'The sun is roughly ahead or behind: no clear side winner.':`Try the ${side} side for less direct side-on sun on this segment.`;const x=200+Math.sin(a*Math.PI/180)*105,y=140-Math.cos(a*Math.PI/180)*105;$('#sun-diagram').innerHTML='<circle cx="200" cy="140" r="112" fill="#f2f3e7" stroke="#c5d1b4" stroke-width="1"/><g fill="#7d9069" font-size="10" text-anchor="middle"><text x="200" y="18">N</text><text x="330" y="144">E</text><text x="200" y="274">S</text><text x="70" y="144">W</text></g>'+`<path d="M${x} ${y}L200 140" stroke="#c7a664" stroke-width="2" stroke-dasharray="4 5"/><g transform="rotate(${h} 200 140)"><rect x="177" y="95" width="46" height="90" rx="12" fill="#f2f4e5" stroke="#668653" stroke-width="2"/><rect x="181" y="99" width="38" height="13" rx="5" fill="#a1b5a7"/><path d="M200 87V66m-6 6l6-6l6 6" stroke="#668653" fill="none" stroke-width="2"/><rect x="${side==='left'?180:216}" y="117" width="4" height="56" fill="${side==='aligned'?'#dce3ce':'#9fbd68'}"/><text x="165" y="148" text-anchor="end" font-size="9" fill="#6b8056">L</text><text x="235" y="148" font-size="9" fill="#6b8056">R</text></g><circle cx="${x}" cy="${y}" r="15" fill="#dfc07d"/><g stroke="#c4a160" stroke-width="2">${Array.from({length:8},(_,i)=>{const t=i*Math.PI/4;return `<path d="M${x+Math.sin(t)*20} ${y+Math.cos(t)*20}l${Math.sin(t)*6} ${Math.cos(t)*6}"/>`;}).join('')}</g>`;$('#sun-diagram').setAttribute('aria-label',`Bus heading ${h} degrees; sun bearing ${a} degrees. ${$('#sun-result').textContent}`);}
$('#heading').oninput=$('#sun-bearing').oninput=renderSun;
$('#model-data').innerHTML='<div class="model-table"><p>Column order: '+criteria.map(c=>c.name).join(' / ')+'</p>'+zones.filter(z=>z.ratings).map(z=>`<p>${z.name}: ${z.ratings.join(' / ')}</p>`).join('')+'<p>Preset weights, in the same order:</p>'+Object.entries(presets).map(([name,w])=>`<p>${name}: ${w.join(' / ')}</p>`).join('')+'<p>0 = unsuitable for that preference; 4 = strongest editorial fit. Low = 0–1; mixed = 2; high = 3–4. The matrix is a qualitative display of these same ratings. Compact buses use the same zone model, not a separate vehicle test.</p></div>';
$('#hero-bus').innerHTML='<ellipse cx="329" cy="312" rx="264" ry="20" fill="#697d4c" opacity=".14"/><path d="M56 159Q56 138 83 138H540Q577 138 587 175L594 271Q594 292 568 292H79Q54 292 54 270Z" fill="#f4f5e9" stroke="#57784e" stroke-width="2"/><path d="M55 235H591V269Q591 292 568 292H79Q54 292 54 270Z" fill="#83a34b"/><path d="M79 152H535Q561 152 572 180V223H79Z" fill="#3d5045"/><g stroke="#859886" stroke-width="2"><path d="M149 153v70M220 153v70M409 153v70M477 153v70M535 153v70"/></g><g fill="#bdc8a4" opacity=".35"><path d="M86 158h40l-33 57h-7Z"/><path d="M170 158h34l-34 57h-12Z"/><path d="M438 158h26l-28 55h-16Z"/></g><rect x="288" y="140" width="50" height="151" fill="#a8b49e" stroke="#71816a"/><g stroke="#697b64" stroke-width="2">'+Array.from({length:9},(_,i)=>`<path d="M${292+i*5} 141v149"/>`).join('')+'</g><g fill="#4a5c4f" stroke="#8c9e84" stroke-width="1.5"><rect x="557" y="180" width="25" height="92"/><rect x="356" y="168" width="35" height="104"/><rect x="238" y="168" width="35" height="104"/><rect x="75" y="168" width="35" height="104"/></g><path d="M569 184v82M373 173v95M255 173v95M92 173v95" stroke="#b1bba1"/><g fill="#26362c" stroke="#f0f2e6" stroke-width="6"><circle cx="151" cy="281" r="30"/><circle cx="437" cy="281" r="30"/><circle cx="522" cy="281" r="30"/></g><g fill="#889783"><circle cx="151" cy="281" r="14"/><circle cx="437" cy="281" r="14"/><circle cx="522" cy="281" r="14"/></g><rect x="472" y="131" width="62" height="14" rx="3" fill="#3d5045"/><text x="503" y="141" text-anchor="middle" font-size="8" fill="#e8df87">LJUBLJANA</text><text x="179" y="252" text-anchor="middle" font-size="10" fill="#f3f6df">LPP-INSPIRED</text><path d="M43 334H608" stroke="#9ba989" stroke-dasharray="4 6"/>';
$('#print').onclick=()=>window.print();renderBus();renderSliders();renderFinder();renderSun();
